import { Button } from "@planet-forge/ui/components/button";
import { useEffect, useState } from "react";
import { useSystems } from "../lib/api";

const GRACE_MS = 12_000;

/**
 * Full-screen status while the simulation engine (the Python sidecar) is being
 * reached. The default systems live in that engine, so until it responds there
 * is nothing to render — this turns the otherwise-blank scene into a clear
 * "initializing" state, and a retryable error if it never comes up.
 */
export function ConnectionStatus() {
	const { data, isError, refetch, isFetching } = useSystems();
	const hasSystems = (data?.systems?.length ?? 0) > 0;
	const [graceElapsed, setGraceElapsed] = useState(false);

	useEffect(() => {
		if (hasSystems) {
			setGraceElapsed(false);
			return;
		}
		const timer = setTimeout(() => setGraceElapsed(true), GRACE_MS);
		return () => clearTimeout(timer);
	}, [hasSystems]);

	if (hasSystems) {
		return null;
	}

	const errored = isError || graceElapsed;

	return (
		<div
			className="absolute inset-0 z-50 grid place-items-center bg-background/40 backdrop-blur-[2px]"
			data-interactive
		>
			<div className="glass flex max-w-sm flex-col items-center gap-3 px-8 py-6 text-center">
				{errored ? (
					<>
						<div className="font-mono text-[#ff9a5a] text-sm uppercase tracking-[0.18em]">
							Simulation engine unavailable
						</div>
						<p className="text-muted-foreground text-xs leading-relaxed">
							The physics engine didn't respond. The default star systems are
							generated by that engine, so nothing can be displayed until it is
							reachable.
						</p>
						<Button
							className="mt-1 font-mono text-xs tracking-[0.16em]"
							disabled={isFetching}
							onClick={() => refetch()}
							variant="outline"
						>
							{isFetching ? "RETRYING…" : "RETRY"}
						</Button>
					</>
				) : (
					<>
						<span className="size-6 animate-spin rounded-full border-2 border-primary/30 border-t-primary" />
						<div className="font-mono text-muted-foreground text-sm uppercase tracking-[0.18em]">
							Initializing simulation core…
						</div>
					</>
				)}
			</div>
		</div>
	);
}
